# 파이썬 데이터 분석 중간시험

## 2부: 넘파이 어레이

__이름:__

__학번:__

#### 주의사항

* 구글 코랩에서 사본을 저장한 다음 문제 풀 것.
* 저장된 사본를 다운로드 한 후에 사이버캠퍼스 과제로 제출할 것.

In [1]:
import numpy as np

np.set_printoptions(precision=6, suppress=True)

보스턴 데이터는 보스턴 시의 506개 구역에 대한 통계 자료를 담고 있다.
먼저 보스턴 데이터를 불러온다.

In [2]:
from sklearn.datasets import load_boston
X = load_boston()

#### 문제 9 (50점)

1부 판다스의 시리즈와 데이터프레임에서 해결한 내용을 모두 동일한 내용으로 넘파이 어레이를 이용하려 해결하라.

In [3]:
boston = X.data
boston

array([[  0.00632,  18.     ,   2.31   , ...,  15.3    , 396.9    ,
          4.98   ],
       [  0.02731,   0.     ,   7.07   , ...,  17.8    , 396.9    ,
          9.14   ],
       [  0.02729,   0.     ,   7.07   , ...,  17.8    , 392.83   ,
          4.03   ],
       ...,
       [  0.06076,   0.     ,  11.93   , ...,  21.     , 396.9    ,
          5.64   ],
       [  0.10959,   0.     ,  11.93   , ...,  21.     , 393.45   ,
          6.48   ],
       [  0.04741,   0.     ,  11.93   , ...,  21.     , 396.9    ,
          7.88   ]])

(5점) 100번부터 104번 행의 5번 열에 `np.nan`을 지정한다.

In [4]:
boston[100:105, 5] = np.nan

__문제 9-3__ (10점)

보스턴 전체 데이터셋에서 수치상으로 5개의 값만 결측치임을 보여주는 표현식을 작성하라.

견본답안: `np.isnan()` 함수를 이용한다.

`np.isnan()` 함수는 결측치 사용 여부를 항목별로 보여주는 부울 어레이를 생성한다.

In [5]:
np.isnan(boston).shape

(506, 13)

정확히 5개의 항목만 결측치이다.

In [6]:
assert np.isnan(boston).sum() == 5

__문제 9-4__ (5점)

결측치가 들어있는 행으로만 이루어진 2차원 넘파이 어레이를 가리키는 `boston_with_nan`을 정의하라.

견본답안: `any(axis=1)` 메서드를 이용한다.

먼저 결측치가 들어 있는 행에 대한 부울 어레이를 생성한다.

In [7]:
boston_nan_row = np.isnan(boston).any(axis=1)
boston_nan_row.shape

(506,)

여전히 5개의 행만 결측치를 포함한다. 

In [8]:
boston_nan_row.sum()

5

이제 부울 인덱싱을 이용하면 결측치가 포함된 행으로만 이루어진 2차원 넘파이 어레이가 아래와 같이 생성된다.

In [9]:
boston_with_nan = boston[boston_nan_row]

assert boston_with_nan.shape == (5, 13)

__문제 9-5__ (5점)

결측치가 들어있지 않은 행으로만 이루어진 2차원 넘파이 어레이를 가리키는 `boston_without_nan`을 정의하라.

견본답안: 역시 부울 인덱싱을 사용한다. 단, 부정(negation) 논리 연산자를 함께 사용한다.

In [10]:
boston_without_nan = boston[~ boston_nan_row]

assert boston_without_nan.shape == (501, 13)

__문제 9-6__ (5점)

`boston_with_nan`이 가리키는 어레이에 사용된 결측치(`NaN`)를 모두 해당 특성의 평균값(mean)으로 대체하라.

견본답안: 부울 인덱싱과 `mean()` 메서드를 활용한다.

먼저 5번 열의 평균값을 구해야 한다.

In [11]:
mean_5c = boston_without_nan[:, 5].mean()
mean_5c

6.283049900199601

In [12]:
boston_with_nan[np.isnan(boston_with_nan)] = mean_5c

결측치가 평균값으로 대체되었음을 확인한다.

In [13]:
boston_with_nan[:, 5]

array([6.28305, 6.28305, 6.28305, 6.28305, 6.28305])

결측치도 전혀 없음을 보이기 위해 결측치가 하나라도 있는지 여부를 묻는 `any()` 메서드를 활용한다.

In [14]:
np.isnan(boston_with_nan).any()

False

__문제 9-7__ (10점)

`AGE` 특성(6번 열)의 값들에서 소수점 이하를 버리고 남은 정수값(`int`)만 이용하는 `AGE_Year` 특성을 추가하라.

견본답안: `astype()` 메서드와 `hstack()` 함수를 이용한다.

먼저 6번 열의 값을 모두 int 형으로 변환한다.

In [15]:
AGE_Year = boston[:, 6].astype(int)

유니버설 함수 `np.int_()`를 이용할 수도 있다.

In [16]:
AGE_Year = np.int_(boston[:, 6])

In [17]:
AGE_Year.dtype

dtype('int64')

In [18]:
AGE_Year[:5]

array([65, 78, 61, 45, 54])

유니버설 함수 `np.floor()` 함수는 소수점 이하를 버리기는 하지만 자료형은 그대로 부동소수점이다.
하지만 어차피 `boston` 어레이에 추가되면 모두 부동소수점으로 자동 형변환되기에 사용해도 전혀 문제 없다.

In [19]:
AGE_Year = np.floor(boston[:, 6])

In [20]:
AGE_Year.dtype

dtype('float64')

In [21]:
AGE_Year[:5]

array([65., 78., 61., 45., 54.])

이제 새로운 열을 추가한다.

In [22]:
boston = np.hstack((boston, AGE_Year[:,np.newaxis]))

아래 방식도 가능하다.

```python
boston = np.c_[boston, AGE_Year]
```

__문제 9-8__ (10점)

AGE 특성(6번 열)을 삭제하라.

견본답안: `np.delete()` 함수 또는 전치 어레이와 부울 인덱싱을 활용한다.

* `np.delete()` 함수를 이용하는 방식은 다음과 같다.

    ```python
    np.delete(boston,6,axis=1)
    ```

* 전치 어레이를 이용하는 방식은 다음과 같다.

2차원 넘파이 어레이에 대한 부울 인덱싱은 부울 어레이의 모양이 1차원인 경우 행에 대해서 인덱싱이 작동한다.
따라서 6번 열을 삭제하려면 전치 어레이의 6번 행을 삭제한 후에 다시 전치시키면 된다.

먼저 boston 어레이를 전치시킨다.

In [23]:
boston_T = boston.T
boston_T.shape

(14, 506)

길이가 14이면서 6번 항목만 False인 부울 어레이를 생성한다.

In [24]:
bool_except6 = np.ones(14).astype(bool)
bool_except6[6] = False
bool_except6

array([ True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True])

이제 부울 인덱싱으로 6번 행을 삭제한 후 다시 전치시키면 6번 열이 삭제된 boston 어레이를 얻는다.

In [25]:
boston = boston_T[bool_except6].T

In [26]:
boston.shape

(506, 13)