# 파이썬 언어, IPython, 주피터 노트북 소개

넘파이 어레이에서 사용되는 부동소수점의 표기법 관련 설정을 먼저 지정한다.

In [1]:
import numpy as np
np.random.seed(12345)
np.set_printoptions(precision=4, suppress=True)

* `np.random.seed()` 함수: 무작위성(randomness) 관련된 함수들이 항상 동일한 결과를 반환하도록 유도
    * `12345`: 자체로는 별 의미 없음.
* `np.set_printoptions()` 함수: 넘파이 어레이 등에서 부동소수점을 화면에 표기하는 여러 설정 지정
    * `precision`: 부동소수점을 표기할 때 필요한 정밀도 지정
    * `suppress`: `e+xx` 등의 표기법 대신에 소수점으로 표기할지 여부 지정. 기본은 `False`이며 `e+xx` 사용.

위 설정은 컴퓨터 다룰 수 있는 매우 작은 값들의 연산 결과를 다양한 방식으로 표기하는 옵션을 지정한다.
사용된 옵션들의 의미를 예제를 통해 살펴보면 다음과 같다.

In [2]:
eps = np.finfo(float).eps

* `np.finfo(float)` 클래스: 부동소수점과 관련해서 컴퓨터가 다룰 수 있는 극한값들을 모아둔 클래스
* `np.finfo(float).eps`: 1보다 큰 부동소수점 중에서 컴퓨터가 다룰 수 있는 가장 작은 부동소수점.

In [3]:
eps

2.220446049250313e-16

In [4]:
x = np.arange(4.)
x

array([0., 1., 2., 3.])

#### `precision=32`

In [5]:
np.set_printoptions(precision=32, suppress=False)

In [6]:
x**2 - (x + eps)**2

array([-4.930380657631324e-32, -4.440892098500626e-16,
        0.000000000000000e+00,  0.000000000000000e+00])

#### `suppress=True`

In [7]:
np.set_printoptions(suppress=True)

In [8]:
x**2 - (x + eps)**2

array([-0.00000000000000000000000000000005,
       -0.0000000000000004440892098500626 ,
        0.                                ,
        0.                                ])

#### `precision=8`,  `suppress=True`

In [9]:
np.set_printoptions(precision=4, suppress=True)

In [10]:
x**2 - (x + eps)**2

array([-0., -0.,  0.,  0.])

## 파이썬 인터프리터

터미널 창에서 `python`이라 입력하고 엔터키를 누르면 파이썬 쉘(python shell)이 실행되며 아래와 같은 결과를 보여준다.

```shell
$ python
Python 3.6.0 | packaged by conda-forge | (default, Jan 13 2017, 23:17:12)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

파이썬 명령문은 아래와 같이 실행한다.

```python
>>> a = 5
>>> print(a)
5
```

파이썬 코드를 담고 있는 파이썬 스크립트 파일은 파일은 `.py` 확장자를 같는다.
예를 들어 아래 코드를 담고 있는 파이썬 스크립트 파일을 `hello_world.py`라 하자.

```python
print('Hello world')
```

위 파일을 바로 실행하려면 터미널 창에서 아래와 같이 명령을 실행한다.

__주의사항:__ `hello_world.py` 파일이 현재 파이썬이 실행되고 있는 폴더에 위치하고 있어야 한다.

```shell
$ python hello_world.py
Hello world
```

## IPython 소개

ipython은 편리성이 추가된 파이썬 쉘(python shell)이며, `ipython` 명령어를 실행한 결과는 다음과 같다.

```shell
$ ipython
Python 3.6.0 | packaged by conda-forge | (default, Jan 13 2017, 23:17:12)
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
```

사용법은 파이썬 쉘과 거의 비슷하지만 보다 편리한 기능이 추가되어 있다.
예를 들어, ipython에서 직접 파이썬 코드가 저장된 파이썬 스크립트 파일을 실행할 수 있다.

**주의사항:** 파이썬 쉘에서는 `>>>` 기호가 프롬프트(prompt) 기호로 사용되었으며,
ipython에서는 `In [1]` 등의 프롬프트가 사용된다.

```ipython
In [1]: %run hello_world.py
Hello world

In [2]:
```

### 주피터 노트북

주피터 노트북은 코드, 텍스트, 데이터 시각화 이미지 등을 지원하는 대화형 문서 양식이다. 
주피터 노트북을 실행하려면 터미널 창에서 아래와 같이 명령을 실행한다.

```shell
$ jupyter notebook
[I 15:20:52.739 NotebookApp] Serving notebooks from local directory:
/home/wesm/code/pydata-book
[I 15:20:52.739 NotebookApp] 0 active kernels
[I 15:20:52.739 NotebookApp] The Jupyter Notebook is running at:
http://localhost:8888/
[I 15:20:52.740 NotebookApp] Use Control-C to stop this server and shut down
all kernels (twice to skip confirmation).
Created new window in existing browser session.
```

주피터 노트북은 ipython을 기본 쉘(shell)로 사용하며, ipython의 기능을 거의 그대로 지원한다. 
예를 들어, `%run` 매직명령어를 아래와 같이 동일하게 사용할 수 있다.

In [11]:
%run hello_world.py

Hello world


__매직명령어:__ 파이썬의 명령어는 아니지만 ipython에서 지원하는 명령어

ipython은 파이썬에서 보다 읽기 편하거나 보기 좋은 형태로 값을 표기한다. 
예를 들어, 아래 `data` 변수에 저장된 사전 자료형의 값을 살펴보자. 

__주의사항:__ 아래 사전 자료형의 내용은 중요하지 않다.

In [12]:
data = {i : np.random.randn() for i in range(7)}

`data`가 가리키는 값을 파이썬에서 보여달라 하면 아래와 같이 보여준다.

```python
>>> data
{0: 0.3880711809981375, 1: -0.11626595239288223, 2: -0.7996499345728855, 3: 0.6638563562390143, 4: -0.39273836157454306, 5: -1.1696376274539204, 6: -0.397267423203786}
```

반면에 ipython에서는 아래와 같이 보여준다.

In [13]:
data

{0: -0.20470765948471295,
 1: 0.47894333805754824,
 2: -0.5194387150567381,
 3: -0.55573030434749,
 4: 1.9657805725027142,
 5: 1.3934058329729904,
 6: 0.09290787674371767}

### 탭 자동완성

탭(`<Tab>`) 키를 이용하여 이름, 명령문 등을 자동완성시킬 수 있다.
탭 키를 잘 활용할 것을 추천한다.

```python
In [1]: an_apple = 27

In [2]: an_example = 42

In [3]: an<Tab>
```

```python
In [3]: b = [1, 2, 3]

In [4]: b.<Tab>
```

```python
In [1]: import datetime

In [2]: datetime.<Tab>
```

```
In [7]: images/<Tab>
```

### 자기관찰

변수 이름 앞이나 뒤에 물음표 기호(`?`)를 붙이면 변수가 가리키는 값에 대한 정보를 출력한다.

In [14]:
b = [1, 2, 3]
b?

In [15]:
print?

함수의 경우 정의에 사용된 문서 문자열(docstring)에 담긴 내용을 함께 출력한다.

In [16]:
def add_numbers(a, b):
    """
    Add two numbers together

    Returns
    -------
    the_sum : type of arguments
    """
    return a + b

In [17]:
add_numbers?

이중 물음표(`??`)를 사용하면 함수의 정의도 함께 보여준다.

In [18]:
add_numbers??

임의의 문자열을 가리키는 와일드카드(wildcard) 기호(`*`)를 사용하면 
함께 사용한 문자와 일치하는 모든 이름 목록을 보여준다.

In [19]:
np.*load*?

### `%run` 명령어

파이썬 스크립트 파일 내용을 불러와서 실행할 수 있다.
예를 들어, 아래 코드가 파이썬 스크립트 파일 `ipython_script_test.py` 에 저정되어 있다고 가정한다.

**주의사항:** python이 실행되는 동일한 디렉토리에 저장되어 있어야 한다. 
즉, 현재 사용하고 있는 주피터 노트북과 동일한 디렉토리에 저정되어 있다고 가정한다.

```python
def f(x, y, z):
    return (x + y) / z

a = 5
b = 6
c = 7.5

result = f(a, b, c)

if __name__ == "__main__":
    print("result:", result)
```

이제 위 파이썬 파일을 실행하면, 
아래 `if` 조건문의 본문이 실행된 결과를 보여준다.

```python
if __name__ == "__main__":
    print("result:", result)
```

In [20]:
%run ipython_script_test.py

result: 1.4666666666666666


또한 위 스크립트 파일에 지정된 변수와 함수를 모두 사용할 수 있다.

In [21]:
c

7.5

In [22]:
result

1.4666666666666666

`%load` 매직명령어는 실행은 하지 않으면서 스크립트 파일의 내용을 그래도 가져오며
사용법은 다음과 같다.

```python
%load ipython_script_test.py
```

주피터 노트북에서 위 명령문을 실행하면 아래 결과에서 보듯이
파이썬 스크립트 파일의 내용을 그대로 가져와서 바로 사용할 수 있도록 해준다.

```python
# %load ipython_script_test.py
def f(x, y, z):
    return (x + y) / z

a = 5
b = 6
c = 7.5

result = f(a, b, c)

if __name__ == "__main__":
    print("result:", result)
```

### 실행중인 코드 중지하기

파이썬 쉘에서 <kbd>Ctrl</kbd>+<kbd>C</kbd> 키 조합을 사용하면 대부분의 코드 실행이 멈춘다.

__참고:__ 주피터 노트북에서 코드 셀(code cell)의 실행을 중지하려면 영어 알파벳 아이(<kbd>I</kbd>) 키를 
두 번 연속 누른다.

### 클립보드에 복사된 코드 실행하기

__참고:__ 책에 설명된 이 기능은 별로 중요하지 않아서 여기서는 생략한다.

### 키보드 단축키

__참고:__ 단축키는 배우는 게 아니라 사용하면서 익혀야 한다.
따라서 여기서는 설명을 생략한다. 
또한 책에서 설명한 단축키는 윈도우용 또는 리눅스용 주피터 노트북에서는 사용할 수 없다. 
반면에 맥(mac)용 주피터 노트북에서는 사용가능하다.

### 매직 명령어

앞서 살펴본 `%run`, `%load` 이외에 ipython은 여러 개의 매직 명령어를 제공한다. 
매직 명령어 또한 단축키 처럼 배우는 게 아니라 필요할 때 사용하면서 익혀야 한다.
여기서는 `timeit` 과 `pwd`를 추가로 살펴본다.

먼저 `%timeit`은 지정된 코드를 여러 번 실행한 다음에 평균 실행 시간을 마이크로 초(microsecond, 10의 6승 분의 1초) 단위로 보여준다.

In [27]:
a = np.random.randn(100, 100)

%timeit np.dot(a, a)

16.3 µs ± 169 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


물음표 기호를 사용하면 해당 매직명령어의 기능과 옵션을 자세하게 알려준다.

In [28]:
%timeit?

`%pwd` 매직 명령어는 현재 파이썬 명령어가 실행되는 디렉토리를 가져와 보여준다.

In [29]:
%pwd

'\\\\wsl$\\Ubuntu\\home\\gslee\\Documents\\GitHub\\python-data-analysis\\notebooks'

가져온 정보를 저장할 수도 있다.

In [30]:
foo = %pwd

foo

'\\\\wsl$\\Ubuntu\\home\\gslee\\Documents\\GitHub\\python-data-analysis\\notebooks'

### `matplotlib` 통합

이제 더 이상 필요하지 않은 옵션이며, 기본으로 지원함.

## 파이썬 기초

### Language Semantics

#### Indentation, not braces

```python
for x in array:
    if x < pivot:
        less.append(x)
    else:
        greater.append(x)
```

```python
a = 5; b = 6; c = 7
```

#### Everything is an object

#### Comments

```python
results = []
for line in file_handle:
    # keep the empty lines for now
    # if len(line) == 0:
    #   continue
    results.append(line.replace('foo', 'bar'))
```

```python
print("Reached this line")  # Simple status report
```

#### Function and object method calls

```
result = f(x, y, z)
g()
```

```
obj.some_method(x, y, z)
```

```python
result = f(a, b, c, d=5, e='foo')
```

#### Variables and argument passing

In [ ]:
a = [1, 2, 3]

In [ ]:
b = a

In [ ]:
a.append(4)
b

```python
def append_element(some_list, element):
    some_list.append(element)
```

```python
In [27]: data = [1, 2, 3]

In [28]: append_element(data, 4)

In [29]: data
Out[29]: [1, 2, 3, 4]
```

#### Dynamic references, strong types

In [ ]:
a = 5
type(a)
a = 'foo'
type(a)

In [ ]:
'5' + 5

In [ ]:
a = 4.5
b = 2
# String formatting, to be visited later
print('a is {0}, b is {1}'.format(type(a), type(b)))
a / b

In [ ]:
a = 5
isinstance(a, int)

In [ ]:
a = 5; b = 4.5
isinstance(a, (int, float))
isinstance(b, (int, float))

#### Attributes and methods

```python
In [1]: a = 'foo'

In [2]: a.<Press Tab>
a.capitalize  a.format      a.isupper     a.rindex      a.strip
a.center      a.index       a.join        a.rjust       a.swapcase
a.count       a.isalnum     a.ljust       a.rpartition  a.title
a.decode      a.isalpha     a.lower       a.rsplit      a.translate
a.encode      a.isdigit     a.lstrip      a.rstrip      a.upper
a.endswith    a.islower     a.partition   a.split       a.zfill
a.expandtabs  a.isspace     a.replace     a.splitlines
a.find        a.istitle     a.rfind       a.startswith
```

In [ ]:
a = 'foo'

In [ ]:
getattr(a, 'split')

#### Duck typing

In [ ]:
def isiterable(obj):
    try:
        iter(obj)
        return True
    except TypeError: # not iterable
        return False

In [ ]:
isiterable('a string')
isiterable([1, 2, 3])
isiterable(5)

if not isinstance(x, list) and isiterable(x):
    x = list(x)

#### Imports

```python
# some_module.py
PI = 3.14159

def f(x):
    return x + 2

def g(a, b):
    return a + b
```

import some_module
result = some_module.f(5)
pi = some_module.PI

from some_module import f, g, PI
result = g(5, PI)

import some_module as sm
from some_module import PI as pi, g as gf

r1 = sm.f(pi)
r2 = gf(6, pi)

#### Binary operators and comparisons

In [ ]:
5 - 7
12 + 21.5
5 <= 2

In [ ]:
a = [1, 2, 3]
b = a
c = list(a)
a is b
a is not c

In [ ]:
a == c

In [ ]:
a = None
a is None

#### Mutable and immutable objects

In [ ]:
a_list = ['foo', 2, [4, 5]]
a_list[2] = (3, 4)
a_list

In [ ]:
a_tuple = (3, 5, (4, 5))
a_tuple[1] = 'four'

### Scalar Types

#### Numeric types

In [ ]:
ival = 17239871
ival ** 6

In [ ]:
fval = 7.243
fval2 = 6.78e-5

In [ ]:
3 / 2

In [ ]:
3 // 2

#### Strings

a = 'one way of writing a string'
b = "another way"

In [ ]:
c = """
This is a longer string that
spans multiple lines
"""

In [ ]:
c.count('\n')

In [ ]:
a = 'this is a string'
a[10] = 'f'
b = a.replace('string', 'longer string')
b

In [ ]:
a

In [ ]:
a = 5.6
s = str(a)
print(s)

In [ ]:
s = 'python'
list(s)
s[:3]

In [ ]:
s = '12\\34'
print(s)

In [ ]:
s = r'this\has\no\special\characters'
s

In [ ]:
a = 'this is the first half '
b = 'and this is the second half'
a + b

In [ ]:
template = '{0:.2f} {1:s} are worth US${2:d}'

In [ ]:
template.format(4.5560, 'Argentine Pesos', 1)

#### Bytes and Unicode

In [ ]:
val = "español"
val

In [ ]:
val_utf8 = val.encode('utf-8')
val_utf8
type(val_utf8)

In [ ]:
val_utf8.decode('utf-8')

In [ ]:
val.encode('latin1')
val.encode('utf-16')
val.encode('utf-16le')

In [ ]:
bytes_val = b'this is bytes'
bytes_val
decoded = bytes_val.decode('utf8')
decoded  # this is str (Unicode) now

#### Booleans

In [ ]:
True and True
False or True

#### Type casting

In [ ]:
s = '3.14159'
fval = float(s)
type(fval)
int(fval)
bool(fval)
bool(0)

#### None

In [ ]:
a = None
a is None
b = 5
b is not None

def add_and_maybe_multiply(a, b, c=None):
    result = a + b

    if c is not None:
        result = result * c

    return result

In [ ]:
type(None)

#### Dates and times

In [ ]:
from datetime import datetime, date, time
dt = datetime(2011, 10, 29, 20, 30, 21)
dt.day
dt.minute

In [ ]:
dt.date()
dt.time()

In [ ]:
dt.strftime('%m/%d/%Y %H:%M')

In [ ]:
datetime.strptime('20091031', '%Y%m%d')

In [ ]:
dt.replace(minute=0, second=0)

In [ ]:
dt2 = datetime(2011, 11, 15, 22, 30)
delta = dt2 - dt
delta
type(delta)

In [ ]:
dt
dt + delta

### Control Flow

#### if, elif, and else

if x < 0:
    print('It's negative')

if x < 0:
    print('It's negative')
elif x == 0:
    print('Equal to zero')
elif 0 < x < 5:
    print('Positive but smaller than 5')
else:
    print('Positive and larger than or equal to 5')

In [ ]:
a = 5; b = 7
c = 8; d = 4
if a < b or c > d:
    print('Made it')

In [ ]:
4 > 3 > 2 > 1

#### for loops

for value in collection:
    # do something with value

sequence = [1, 2, None, 4, None, 5]
total = 0
for value in sequence:
    if value is None:
        continue
    total += value

sequence = [1, 2, 0, 4, 6, 5, 2, 1]
total_until_5 = 0
for value in sequence:
    if value == 5:
        break
    total_until_5 += value

In [ ]:
for i in range(4):
    for j in range(4):
        if j > i:
            break
        print((i, j))

for a, b, c in iterator:
    # do something

#### while loops

x = 256
total = 0
while x > 0:
    if total > 500:
        break
    total += x
    x = x // 2

#### pass

if x < 0:
    print('negative!')
elif x == 0:
    # TODO: put something smart here
    pass
else:
    print('positive!')

#### range

In [ ]:
range(10)
list(range(10))

In [ ]:
list(range(0, 20, 2))
list(range(5, 0, -1))

seq = [1, 2, 3, 4]
for i in range(len(seq)):
    val = seq[i]

sum = 0
for i in range(100000):
    # % is the modulo operator
    if i % 3 == 0 or i % 5 == 0:
        sum += i

#### Ternary expressions

value = 

if 

In [ ]:
x = 5
'Non-negative' if x >= 0 else 'Negative'