# 4장 넘파이 4편: 고급 넘파이

## 주요 내용

부록 A(p. 587)의 내용 중 가장 많이 사용되는 고급 기능을 다룬다.

* 어레이 조작: 모양 변형, 어레이 쪼개기/쌓기
* 브로드캐스팅

## 기본 설정

`numpy` 모듈과 시각화 도구 모듈인 `matplotlib.pyplot`에 대한 기본 설정을 지정한다.

In [1]:
# 넘파이
import numpy as np
# 램덤 시드
np.random.seed(12345)
# 어레이 사용되는 부동소수점들의 정확도 지정
np.set_printoptions(precision=4, suppress=True)

# 파이플롯
import matplotlib.pyplot as plt
# 도표 크기 지정
plt.rc('figure', figsize=(10, 6))

## A.2 어레이 조작 고급 기법 (p. 590)

어레이를 조작하는 몇 가지 중요한 고급 기법을 살펴본다. 

### A.2.1 어레이 모양 변형 (p. 590)

#### `reshape()` 메서드

`reshape()` 메서드를 활용하여 지정된 튜플의 모양으로 주어진 어레이의 모양을 변형한다.
단, 항목의 수가 변하지 않도록 모양을 지정해야 한다.

예를 들어, 길이가 8인 1차원 어레이가 다음과 같다.

In [2]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

이제 (4, 2) 모양의 2차원 어레이로 모양을 변형할 수 있다.

In [3]:
arr.reshape((4, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

항목의 수만 같으면 임의의 차원의 어레이를 임의의 차원의 어레이로 변형시킬 수 있다.

In [4]:
arr.reshape((4, 2)).reshape((2, 2, 2))

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

#### `-1`의 역할

어레의 모양을 지정할 때 튜플의 특정 위치에 -1을 사용할 수 있다.
그러면 그 위치의 값은 튜플의 다른 항목의 정보를 이용하여 자동으로 지정된다.
예를 들어, 아래 코드에서 -1은 4를 의미한다. 
이유는 20개의 항목을 5개의 행으로 이루어진 2차원 어레이로 지정하려면 열은 4개 있어야 하기 때문이다.

In [5]:
arr = np.arange(20)
arr.reshape((5, -1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [6]:
arr.reshape((5, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

동일한 이유로 아래에서 -1은 5를 의미한다.

In [7]:
arr.reshape((2, -1, 2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [8]:
arr.reshape((2, 5, 2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

### A.3.1 차원 추가(p. 604)

어레이에 임의의 축을 추가하는 방식으로 1차원 커진 어레이를 생성할 수 있다.
어느 축을 지정하느냐에 따라 다른 모양을 갖게 된다.

#### 예제

다음 길이가 3인 1차원 어레이를 이용하자.

* `np.random.normal()` 함수는 `np.random.randn()` 함수를 일반화하여 정균분포를 따르면서
    무작위 수를 생성한다. 
    평균값과 표준편차를 지정할 수 있으며, 기본값은 평균값 0, 표준편차 1로 표준 정규분포를 따르도록 한다.

In [9]:
arr_1d = np.random.normal(size=3)
arr_1d

array([-0.2047,  0.4789, -0.5194])

아래 코드는 열 관련 축을 추가한다.

In [10]:
arr_1d[:, np.newaxis]

array([[-0.2047],
       [ 0.4789],
       [-0.5194]])

`reshape()` 메소드로도 동일한 결과를 얻을 수 있다.

In [11]:
arr_1d.reshape((3, 1))

array([[-0.2047],
       [ 0.4789],
       [-0.5194]])

아래 코드는 행 관련 축을 추가한다.

In [12]:
arr_1d[np.newaxis, :]

array([[-0.2047,  0.4789, -0.5194]])

In [13]:
arr_1d.reshape((1,3))

array([[-0.2047,  0.4789, -0.5194]])

#### 예제

2차원 어레이에 축을 추가하면 3차원 어레이가 생성되며, 작동방식은 앞서와 동일하다.

In [14]:
arr = np.random.randn(4, 3)
arr

array([[-0.5557,  1.9658,  1.3934],
       [ 0.0929,  0.2817,  0.769 ],
       [ 1.2464,  1.0072, -1.2962],
       [ 0.275 ,  0.2289,  1.3529]])

In [15]:
arr[:,:,np.newaxis].shape

(4, 3, 1)

In [16]:
arr[:,:,np.newaxis]

array([[[-0.5557],
        [ 1.9658],
        [ 1.3934]],

       [[ 0.0929],
        [ 0.2817],
        [ 0.769 ]],

       [[ 1.2464],
        [ 1.0072],
        [-1.2962]],

       [[ 0.275 ],
        [ 0.2289],
        [ 1.3529]]])

In [17]:
arr[:,np.newaxis,:].shape

(4, 1, 3)

In [18]:
arr[:,np.newaxis,:]

array([[[-0.5557,  1.9658,  1.3934]],

       [[ 0.0929,  0.2817,  0.769 ]],

       [[ 1.2464,  1.0072, -1.2962]],

       [[ 0.275 ,  0.2289,  1.3529]]])

#### `ravel()` 메서드와 `flatten()` 메서드

두 메서드 모두 1차원 어레이를 반환한다. 
즉, 차원을 모두 없앤다.

In [19]:
arr = np.arange(15).reshape((5, 3))
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [20]:
arr1 = arr.ravel()
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
arr2 = arr.flatten()
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

차이점은 `ravel()` 메서드는 뷰(view)를 사용하는 반면에 `flatten()` 메서드는 어레이를 새로 생성한다.
예를 들어, 아래처럼 `arr1`의 항목을 변경하면 `arr`의 항목도 함께 변경된다.

In [22]:
arr1[0] = -1
arr

array([[-1,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

`arr2`은 `arr`과 전혀 상관이 없다.

In [23]:
arr2[0] = -7
arr

array([[-1,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

### A.2.3 어레이 쪼개기/쌓기 (p. 594)

#### `np.split()` 함수

어레이를 지정된 기준에 따라 여러 개의 어레이로 쪼갠다.
반환값은 쪼개진 어레이들의 리스트다.

아래 예제를 살펴보자.

In [24]:
arr = np.random.randn(7, 5)
arr

array([[ 0.8864, -2.0016, -0.3718,  1.669 , -0.4386],
       [-0.5397,  0.477 ,  3.2489, -1.0212, -0.5771],
       [ 0.1241,  0.3026,  0.5238,  0.0009,  1.3438],
       [-0.7135, -0.8312, -2.3702, -1.8608, -0.8608],
       [ 0.5601, -1.2659,  0.1198, -1.0635,  0.3329],
       [-2.3594, -0.1995, -1.542 , -0.9707, -1.307 ],
       [ 0.2863,  0.378 , -0.7539,  0.3313,  1.3497]])

`np.split()` 함수의 인자는 정수이거나 정수들의 리스트가 사용된다.
먼저, 정수 리스트가 들어오면 축이 정한 방향으로 리스트에 포함된 정수를 이용하여 여러 개의 구간으로 쪼갠다.

아래 코드는 행을 기준으로 행의 인덱스를 0-1, 2, 3-4, 5-7 네 개의 구간으로 쪼갠다.
따라서 결과는 네 개의 어레이로 이루어진 리스트가 되며,
각 어레의 모양은 다음과 같다.

```python
(2, 5), (1, 5), (2, 5), (3, 5)
```

In [25]:
np.split(arr, [2, 3, 5],axis=0)

[array([[ 0.8864, -2.0016, -0.3718,  1.669 , -0.4386],
        [-0.5397,  0.477 ,  3.2489, -1.0212, -0.5771]]),
 array([[0.1241, 0.3026, 0.5238, 0.0009, 1.3438]]),
 array([[-0.7135, -0.8312, -2.3702, -1.8608, -0.8608],
        [ 0.5601, -1.2659,  0.1198, -1.0635,  0.3329]]),
 array([[-2.3594, -0.1995, -1.542 , -0.9707, -1.307 ],
        [ 0.2863,  0.378 , -0.7539,  0.3313,  1.3497]])]

반면에 열을 기준으로 0, 1-2, 3-4 3개의 구간으로 쪼개면 다음과 같으며,
각 어레이의 모양은 다음과 같다.

```python
(7, 1) (7, 2), (7, 2)
```

In [26]:
np.split(arr, [1, 3],axis=1)

[array([[ 0.8864],
        [-0.5397],
        [ 0.1241],
        [-0.7135],
        [ 0.5601],
        [-2.3594],
        [ 0.2863]]),
 array([[-2.0016, -0.3718],
        [ 0.477 ,  3.2489],
        [ 0.3026,  0.5238],
        [-0.8312, -2.3702],
        [-1.2659,  0.1198],
        [-0.1995, -1.542 ],
        [ 0.378 , -0.7539]]),
 array([[ 1.669 , -0.4386],
        [-1.0212, -0.5771],
        [ 0.0009,  1.3438],
        [-1.8608, -0.8608],
        [-1.0635,  0.3329],
        [-0.9707, -1.307 ],
        [ 0.3313,  1.3497]])]

#### `np.vsplit()`/`np.hsplit()` 함수

두 함수는 `np.split()` 함수에 축을 각각 0과 1로 지정한 함수이다.

* `np.vsplit(arr, z)` = `np.split(arr, z, axis=0)`

In [27]:
np.vsplit(arr, [2, 3, 5])

[array([[ 0.8864, -2.0016, -0.3718,  1.669 , -0.4386],
        [-0.5397,  0.477 ,  3.2489, -1.0212, -0.5771]]),
 array([[0.1241, 0.3026, 0.5238, 0.0009, 1.3438]]),
 array([[-0.7135, -0.8312, -2.3702, -1.8608, -0.8608],
        [ 0.5601, -1.2659,  0.1198, -1.0635,  0.3329]]),
 array([[-2.3594, -0.1995, -1.542 , -0.9707, -1.307 ],
        [ 0.2863,  0.378 , -0.7539,  0.3313,  1.3497]])]

* `np.hsplit(arr, z)` = `np.split(arr, z, axis=1)`

In [28]:
np.hsplit(arr, [1, 3])

[array([[ 0.8864],
        [-0.5397],
        [ 0.1241],
        [-0.7135],
        [ 0.5601],
        [-2.3594],
        [ 0.2863]]),
 array([[-2.0016, -0.3718],
        [ 0.477 ,  3.2489],
        [ 0.3026,  0.5238],
        [-0.8312, -2.3702],
        [-1.2659,  0.1198],
        [-0.1995, -1.542 ],
        [ 0.378 , -0.7539]]),
 array([[ 1.669 , -0.4386],
        [-1.0212, -0.5771],
        [ 0.0009,  1.3438],
        [-1.8608, -0.8608],
        [-1.0635,  0.3329],
        [-0.9707, -1.307 ],
        [ 0.3313,  1.3497]])]

#### `np.concatenate()` 함수

두 개의 어레이를 이어 붙이다.
지정되는 축에 따라 좌우로 또는 상하로 이어붙인다.

아래 두 어레이가 주어졌다고 가정하다.

In [29]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

위아래로 이어붙이려면 축을 0으로 정한다.

__주의사항:__ 인자가 길이가 2인 리스트이다.

In [31]:
np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

좌우로 이어붙이려면 축을 1로 정한다.

In [32]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

#### `np.vstack()`/`np.hstack()` 함수

두 함수는 `np.concatenate()` 함수에 축을 각각 0과 1로 지정한 함수이다.

__주의사항:__ 인자가 길이가 2인 튜플이다.

* `np.vstack((x, y))` = `np.concatenate([x, y], axis=0)`

In [33]:
np.vstack((arr1, arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

* `np.hstack((x, y))` = `np.concatenate([x, y], axis=1)`

In [34]:
np.hstack((arr1, arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

#### `np.r_()`/`np.c_()` 객체

`vstack()`/`hstack()` 과 동일한 기능을 수행하는 특수한 객체들이다.

아래 세 개의 어레이를 이용하여 사용법을 살펴본다.

In [35]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [36]:
arr1 = np.arange(6).reshape((3, 2))
arr1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [37]:
arr2 = np.random.randn(3, 2)
arr2

array([[ 0.0699,  0.2467],
       [-0.0119,  1.0048],
       [ 1.3272, -0.9193]])

아래 코드는 `np.vstack((arr1, arr2))`와 동일하다.

In [38]:
np.r_[arr1, arr2]

array([[ 0.    ,  1.    ],
       [ 2.    ,  3.    ],
       [ 4.    ,  5.    ],
       [ 0.0699,  0.2467],
       [-0.0119,  1.0048],
       [ 1.3272, -0.9193]])

In [39]:
np.vstack([arr1, arr2])

array([[ 0.    ,  1.    ],
       [ 2.    ,  3.    ],
       [ 4.    ,  5.    ],
       [ 0.0699,  0.2467],
       [-0.0119,  1.0048],
       [ 1.3272, -0.9193]])

아래 코드는 `np.hstack((arr1, arr2))`와 동일하다.

In [40]:
np.c_[arr1, arr2]

array([[ 0.    ,  1.    ,  0.0699,  0.2467],
       [ 2.    ,  3.    , -0.0119,  1.0048],
       [ 4.    ,  5.    ,  1.3272, -0.9193]])

In [41]:
np.hstack((arr1, arr2))

array([[ 0.    ,  1.    ,  0.0699,  0.2467],
       [ 2.    ,  3.    , -0.0119,  1.0048],
       [ 4.    ,  5.    ,  1.3272, -0.9193]])

행 또는 열의 크기를 적절하게 맞출 수 있는 어떤 조합도 가능하다.

In [42]:
np.c_[np.r_[arr1, arr2], arr]

array([[ 0.    ,  1.    ,  0.    ],
       [ 2.    ,  3.    ,  1.    ],
       [ 4.    ,  5.    ,  2.    ],
       [ 0.0699,  0.2467,  3.    ],
       [-0.0119,  1.0048,  4.    ],
       [ 1.3272, -0.9193,  5.    ]])

## A.3 브로드캐스팅 (p. 601)

#### 예제

In [43]:
arr = np.arange(6).reshape((2,3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

`arr * 4` 아래 어레이의 곱셈과 동일하다.

<img src="https://github.com/codingalzi/pydata/blob/master/notebooks/images/broadcasting14.png?raw=true" style="width:300px;">

In [44]:
arr * 4

array([[ 0,  4,  8],
       [12, 16, 20]])

#### 예제

In [45]:
arr2 = np.arange(4).reshape((4,1)).repeat(3,axis=1)
arr2

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [46]:
arr3 = np.arange(1, 4)
arr3

array([1, 2, 3])

In [47]:
arr2 + arr3

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

<img src="https://github.com/codingalzi/pydata/blob/master/notebooks/images/broadcasting10.png?raw=true" style="width:400px;">

In [48]:
arr3a = np.arange(1, 4).reshape((1,3))
arr3a

array([[1, 2, 3]])

In [49]:
arr2 + arr3a

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

<img src="https://github.com/codingalzi/pydata/blob/master/notebooks/images/broadcasting10a.png?raw=true" style="width:400px;">

#### 예제

In [50]:
arr4 = np.arange(1, 5).reshape((4,1))
arr4

array([[1],
       [2],
       [3],
       [4]])

In [51]:
arr2 + arr4

array([[1, 1, 1],
       [3, 3, 3],
       [5, 5, 5],
       [7, 7, 7]])

<img src="https://github.com/codingalzi/pydata/blob/master/notebooks/images/broadcasting11.png?raw=true" style="width:400px;">

#### 예제

In [52]:
arr6 = np.arange(24).reshape((3, 4, 2))
arr6

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [53]:
arr7 = np.arange(8).reshape((4, 2))
arr7

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [54]:
arr6 + arr7

array([[[ 0,  2],
        [ 4,  6],
        [ 8, 10],
        [12, 14]],

       [[ 8, 10],
        [12, 14],
        [16, 18],
        [20, 22]],

       [[16, 18],
        [20, 22],
        [24, 26],
        [28, 30]]])

<img src="https://github.com/codingalzi/pydata/blob/master/notebooks/images/broadcasting12.png?raw=true" style="width:400px;">

#### 예제

In [55]:
arr = np.random.randn(4, 3)
arr

array([[-1.5491,  0.0222,  0.7584],
       [-0.6605,  0.8626, -0.01  ],
       [ 0.05  ,  0.6702,  0.853 ],
       [-0.9559, -0.0235, -2.3042]])

In [56]:
arr.mean(0)

array([-0.7789,  0.3829, -0.1757])

In [57]:
demeaned = arr - arr.mean(0)
demeaned

array([[-0.7702, -0.3607,  0.9341],
       [ 0.1183,  0.4797,  0.1657],
       [ 0.8289,  0.2873,  1.0287],
       [-0.177 , -0.4064, -2.1285]])

In [58]:
demeaned.mean(0)

array([ 0.,  0., -0.])

#### 예제

In [59]:
arr

array([[-1.5491,  0.0222,  0.7584],
       [-0.6605,  0.8626, -0.01  ],
       [ 0.05  ,  0.6702,  0.853 ],
       [-0.9559, -0.0235, -2.3042]])

In [60]:
row_means = arr.mean(1)
row_means

array([-0.2562,  0.064 ,  0.5244, -1.0945])

In [61]:
row_means.reshape((4, 1))

array([[-0.2562],
       [ 0.064 ],
       [ 0.5244],
       [-1.0945]])

In [62]:
demeaned = arr - row_means.reshape((4, 1))

In [63]:
demeaned.mean(1)

array([-0., -0., -0., -0.])

### A.3.2 브로드캐스팅으로 어레이에 값 대입하기 (p. 606)

In [64]:
arr = np.zeros((4, 3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [65]:
arr[:] = 5
arr

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [66]:
col = np.array([1.28, -0.42, 0.44, 1.6])

In [67]:
arr[:] = col[:, np.newaxis]
arr

array([[ 1.28,  1.28,  1.28],
       [-0.42, -0.42, -0.42],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])

In [68]:
arr[:2] = [[-1.37], [0.509]]
arr

array([[-1.37 , -1.37 , -1.37 ],
       [ 0.509,  0.509,  0.509],
       [ 0.44 ,  0.44 ,  0.44 ],
       [ 1.6  ,  1.6  ,  1.6  ]])

## 과제

아래 코드는 인터넷 데이터 저장소로부터 아이리스(붓꽃) 데이터(`iris.data`)를 
2차원 넘파이 어레이로 불러온다.

In [69]:
# 아이리스(붓꽃) 데이터 불러오기
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='str')

`iris.data` 파일에는 아래 형식의 데이터가 150개 들어 있다. 

```python
5.1,3.5,1.4,0.2,Iris-setosa
```

하나의 데이터에 사용된 값들은 하나의 아이리스(붓꽃)에 대한 꽃잎, 꽃받침과 관련된 특성(features)과 품종을 나타내며,
보다 구체적으로 아래 순서를 따른다.

```
꽃받침 길이, 꽃받침 너비, 꽃잎 길이, 꽃잎 너비, 품종
```

In [70]:
iris.shape

(150, 5)

길이와 너비를 저장하는 특성들은 숫자로 저장되어 있었지만 위 코드는 문자열로 저장된 품종 특성과의 자료형을 통일시키기 위해
모두 문자열 자료형으로 불러왔다.
처음 5개 데이터를 확인하면 다음과 같다.

__참고:__ `'<U15'`는 길이가 최대 15인 유니코드 문자열 자료형을 나타낸다.

In [71]:
iris[:5]

array([['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3.0', '1.4', '0.2', 'Iris-setosa'],
       ['4.7', '3.2', '1.3', '0.2', 'Iris-setosa'],
       ['4.6', '3.1', '1.5', '0.2', 'Iris-setosa'],
       ['5.0', '3.6', '1.4', '0.2', 'Iris-setosa']], dtype='<U15')

수치형 데이터와 품종 데이터를 분리해서 각각 (150,4), (150,) 모양의 어레이를 생성하자.
이때 수치형 데이터는 `'f8'`, 즉 `'float64'` 자료형을 사용하도록 한다.

In [72]:
iris_features = iris[:,:4].astype('f8')
iris_labels = iris[:, 4]

In [73]:
iris_features[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

150개의 데이터는 아래 세 개의 품종으로 구분되며, 각각 50개씩 아래 언급된 순서대로 구분되어 있다.

```
'Iris-setosa', 'Iris-versicolor', 'Iris-virginica'
```

즉, 0번, 50번, 100번부터 각 품종의 데이터가 시작된다.

In [74]:
iris_labels[::50]

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype='<U15')

In [75]:
iris_labels[:5]

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa'], dtype='<U15')

In [76]:
iris_labels[50:55]

array(['Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor'], dtype='<U15')

In [77]:
iris_labels[100:105]

array(['Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica'], dtype='<U15')

__과제 1.__ 꽃잎 길이(2번 열)가 1.5보다 크거나 꽃받침 길이(0번 열)가 5.0보다 작은 데이터만 추출하라.

In [ ]:
# None을 적절한 부울 표현식으로 대체하라.

mask = None
iris_features[mask]

__과제 2.__ 꽃받침 길이(0번 열)와 꽃잎 길이(2번 열) 사이의 상관관계를 계산하라.

힌트: 넘파이의 적절한 함수를 활용한다. 상관계수에 대한 설명은 [위키백과: 상관분석](https://ko.wikipedia.org/wiki/상관_분석)을 참고한다.

In [ ]:
# 적절한 넘파이 함수를 호출하라.


__과제 3.__ 아래 식으로 계산된 값을 갖는 새로운 열(column)이 추가된 2차원 어레이  `iris_features_added`를 생성하라.

$$\frac{\text{원주율} \times \text{꽃잎길이} \times \text{꽃받침길이}^2}{3} $$

힌트: `np.stack()` 함수를 활용할 수 있다.

In [ ]:
# pass와 None을 각각 적절한 코드와 표현식으로 대체하라.

pass
iris_features_added = None

assert iris_features_added.shape == (150, 5)
iris_features_added[:5]

__과제 4.__ `Iris_versicolor` 품종에 해당하는 데이터만 `iris_features`로부터 추출하라. 

In [ ]:
# None을 적절한 부울 표현식으로 대체하라.

mask = None
iris_features[mask][:5]

__과제 5.__ 꽃받침 길이(0번 열)의 평균값(mean), 중앙값(median), 표준편차(standard deviation)를 구하라.

In [ ]:
# None을 적절한 표현식으로 대체하라.

petal_length_mean = None
petal_length_median = None
petal_length_std = None

print(petal_length_mean, petal_length_median, petal_length_std)

__과제 6.__ 세 개의 품종 별 꽃받침 너비(1번 열)의 평균값을 계산하여 아래 어레이와 동일한 모양을 갖는 
어레이 `iris_kind_sepal_length`를 생성하라.

```
[['Iris-setosa', 3.418],
 ['Iris-versicolor', 2.770],
 ['Iris-virginica', 2.974]]
```

In [ ]:
# pass와 None을 각각 적절한 코드와 표현식으로 대체하라.

pass
iris_kind_sepal_length = None

iris_kind_sepal_length

__과제 7.__ 꽃잎 너비(3번 열)에 사용된 값을 모두 0과 1사이의 값으로 변환하라. 

힌트: 꽃잎 너비 등 하나의 특성에 속하는 값을 모두 0과 1사이의 값으로 변환하는 작업을 정규화(normalization)라 한다.
정규화에 대한 설명은 [정규화/표준화](https://rucrazia.tistory.com/90)를 참고하라.

In [ ]:
# None을 적절한 부울 표현식으로 대체하라.

iris_features_normalized = None

iris_features_normalized[:5]

__과제 8.__ `iris_features`에 사용된 모든 값을 특성 별로 표준화(standardization)하라. 

힌트: 표준화에 대한 설명은 [정규화/표준화](https://rucrazia.tistory.com/90)를 참고하라.

In [ ]:
# None을 적절한 부울 표현식으로 대체하라.

iris_features_standardized = None

iris_features_standardized[:5]